server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod
  redis:
    host: xxxxxx
    port: 6379
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://xxxxxx:3306/ordersystem
    username: xxx
    password: yyy
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show_sql: true
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

cloud:
  aws:
    credentials:
      access-key: xx
      secret-key: yy
    region:
      static: ap-northeast-2
    s3:
      bucket: bradkim-ordersystem-product-image


jwt:
  expirationAt: 1000
  secretKeyAt: xxxx
  expirationRt: 10000
  secretKeyRt: yyyy

